## Hilo cuántico 2D en diferencias finitas 


Referencias https://physics.stackexchange.com/questions/292492/finite-difference-method-applied-to-the-2d-time-independent-schr%C3%B6dinger-equation


https://scicomp.stackexchange.com/questions/5655/2d-schr%C3%B6dinger-time-independent-finite-difference-and-eigenvalues



![alt text](2finite.png "Title")





![alt text](finite.png "Title")


En este caso la ecuación esta adimencionalizada 

In [128]:
import numpy as np 

L = 4.
a = 2.
dx = 1. 
dy = 1.
v0 = 30.
n = 10


def fbox(x,y,a,v0,dx,dy):
    
    if abs(x)<a/2. and abs(y)<a/2.:
        return 0
        
    else:
        return v0

    
# Suma de Potencial
x =  np.arange(-L/2,L/2.,dx )
y =  np.arange(-L/2,L/2.,dy )
vec = []
for j in range(len(x)):
    for i in range(len(x)):
        vec+=[4.+fbox(x[i],y[i],a,v0,dx,dy)]
n = len(vec)
        
      
Matrix = np.zeros((n,n))
for j in range(n):
        Matrix[j,j]=vec[j]
    

b=[34,-1,0,-1]+list(np.zeros(np.shape(Matrix)[0]-4))
Matrix[0]=b

In [129]:
# Fill Matrix 
c =0
for j in range(n):
    for i in range(n-1):
        if i==j:
            Matrix[j,i+1]=-1
            c+=1
            if c==3:
                Matrix[j,i+1]=0
                c=0 
c=0
for j in range(1,n):
    for i in range(n):
        if i==j:
            Matrix[j,i-1]=-1
            c+=1
            if c==3:
                Matrix[j,i-1]=0
                c=0 
                
for j in range(n):
    for i in range(n-3):
        if i==j:
            Matrix[j,i+3]=-1
            
for j in range(3,n):
    for i in range(n):
        if i==j:
            Matrix[j,i-3]=-1
            

        

In [130]:
print(Matrix)

[[34. -1.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. 34. -1.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  4.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0. 34. -1.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0. -1. 34. -1.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0. -1. 34.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  4. -1.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0. -1. 34. -1.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0. -1. 34.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0. 34. -1.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0. -1.  4. -1.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0. -1. 34.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0. 34. -1.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0. -1. 34. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0. -1.  4. 

In [125]:
eigenvalues,eigenvectors = np.linalg.eig(Matrix)

In [127]:
eigenvalues

array([ 3.79413605,  3.9915446 ,  3.93326023,  3.91531052, 36.52968588,
       31.5524061 , 32.42379437, 32.29875906, 35.60905797, 35.76709715,
       33.51331315, 34.52236367, 34.09702191, 34.03580724, 34.00202962,
       34.01441246])