In [26]:
import numpy as np
n = 10
L = 4.
a = 2.
dx = 0.01 
v0 = 30.
Matrix = np.zeros((n,n))
# inicial 
px0 = 0 

x = np.linspace(-L/2,L/2.,dx)

Matrix[0,0]= 2. +v0*dx**2
Matrix[0,1]= -1. 
Matrix[n-1,n-1]= 2.
Matrix[n-1,n-2]= -1.

for i in range(1,n-1):
    for j in range(1,n-1):
        if i ==j:
            #if -L/2.<x[i]<-a/2. and  a/2.<x[i]<L/2:
             #   Matrix[i,j] = 2. + Vo*dx**2
            #else : 
            Matrix[i,j] = 2.
            Matrix[i,j+1] = -1
            Matrix[i,j-1] = -1
        
    

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:11: DeprecationWarning: object of type <type 'float'> cannot be safely interpreted as an integer.


In [27]:
print(Matrix)

[[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2.]]
